your-project/
└── public/
    └── _redirects
/*    /index.html   200
npm run build
Processing _redirects file...

[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
git add netlify.toml
git commit -m "Add netlify.toml for proper SPA redirect"
git push
